---
- name: include os specific variables
  include_vars: "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"

- name: install epel repo
  yum:
    name: "{{ item.url }}"
    state: present
  with_items:
    - url: "{{ epel_repo }}"

- name: install python-pip
  yum:
    name: python-pip
    state: present

- name: install supervisord and its dependencies
  pip:
    name: "{{ item.name }}"
    version: "{{ item.version}}"
  with_items:
    - name: 'meld3'
      version: '1.0.0'
    - name: 'supervisor'
      version: '3.3.1'

- name: copy supervisord startup script
  template:
    src: "{{ supervisord_init_src }}"
    dest: "{{ supervisord_init_dst }}"
    mode: 0644

- name: create supervisord log directory
  file:
    path: /var/log/supervisor
    state: directory
    mode: 0755

- name: copy supervisord main config
  template:
    src: supervisord.conf.j2
    dest: /etc/supervisord.conf
  notify: restart supervisord
